name: "Publish Image to Repository"
description: "Publishes the image to ghcr.io docker image repository"
inputs:
  image:
    required: true
    description: "The image to use"
  token:
    required: true
    description: "The Github secret token to login to package repository"

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
        
      - name: Run pre-script if present
        shell: bash
        run: |
          (chmod -f +x ${{ inputs.image }}/.prescript || true) 2>/dev/null
          [ -x ${{ inputs.image }}/.prescript ] && bash ${{ inputs.image }}/.prescript || true
        
      - name: Inject image tag variables
        shell: bash
        run: |
          (chmod -f +x ${{ inputs.image }}/.imagetag || true) 2>/dev/null
          [ -f ${{ inputs.image }}/.imagetag ] && IMAGE_VER=`${{ inputs.image }}/.imagetag` || IMAGE_VER=`date +'0.%y%j.%H%M%S'`
          echo "IMAGE_VER=$IMAGE_VER" >> $GITHUB_ENV

      - name: Set env
        shell: bash      
        run: |
          export IMAGE=ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ inputs.image }}:${{ env.IMAGE_VER }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: "1"
        with:
          context: ${{ inputs.image }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE }}
          cache-from: type=registry,ref=ghcr.io/akarthik10/f095a4d8-docker-build-cache:${{ inputs.image }}
          cache-to: type=registry,ref=ghcr.io/akarthik10/f095a4d8-docker-build-cache:${{ inputs.image }},mode=max
