#!/bin/bash
set -euo pipefail

function run_commands {
	COMMANDS=$1
	while IFS= read -r cmd; do echo $cmd && eval $cmd ; done < <(printf '%s\n' "$COMMANDS")
}

run_commands "${RCLONE_COPYCONFIG_COMMAND:-}"
run_commands "${RCLONE_ABOUT_COMMAND:-}"

run_commands "${RESTIC_PREBACKUP_COMMAND:-}"
run_commands "${RESTIC_BACKUP_COMMAND:-}"

run_commands "${RESTIC_FORGET_COMMAND:-}"
run_commands "${RESTIC_CHECK_COMMAND:-}"
