name: Matrix Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  changed-files:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      skip: ${{ steps.set-skip.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true
          dir_names: true
          dir_names_max_depth: 1
          files_ignore: |
            .github/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"container\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
      - id: set-skip
        run: echo "skip=${{ steps.changed-files.outputs.all_changed_files != '[]'  }}" >> "$GITHUB_OUTPUT"        
      - name: List reason for run
        run: echo "${{ github.event_name }} triggered this run"

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.skip == false }}
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.container }}
